/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VizhunRouteImport } from './routes/vizhun'
import { Route as Pmp24q40mRouteImport } from './routes/pmp24q40m'
import { Route as PmpPracticeRouteImport } from './routes/pmp-practice'
import { Route as People_test_reviewRouteImport } from './routes/people_test_review'
import { Route as People_testRouteImport } from './routes/people_test'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LearningTransformationRouteImport } from './routes/learning-transformation'
import { Route as EnterpriseTransformationRouteImport } from './routes/enterprise-transformation'
import { Route as ContractorOnboardingRouteImport } from './routes/contractor-onboarding'
import { Route as ContractorAdminRouteImport } from './routes/contractor-admin'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerTransformationRouteImport } from './routes/career-transformation'
import { Route as AygulQuizRouteImport } from './routes/aygul-quiz'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const VizhunRoute = VizhunRouteImport.update({
  id: '/vizhun',
  path: '/vizhun',
  getParentRoute: () => rootRouteImport,
} as any)
const Pmp24q40mRoute = Pmp24q40mRouteImport.update({
  id: '/pmp24q40m',
  path: '/pmp24q40m',
  getParentRoute: () => rootRouteImport,
} as any)
const PmpPracticeRoute = PmpPracticeRouteImport.update({
  id: '/pmp-practice',
  path: '/pmp-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const People_test_reviewRoute = People_test_reviewRouteImport.update({
  id: '/people_test_review',
  path: '/people_test_review',
  getParentRoute: () => rootRouteImport,
} as any)
const People_testRoute = People_testRouteImport.update({
  id: '/people_test',
  path: '/people_test',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningTransformationRoute = LearningTransformationRouteImport.update({
  id: '/learning-transformation',
  path: '/learning-transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseTransformationRoute =
  EnterpriseTransformationRouteImport.update({
    id: '/enterprise-transformation',
    path: '/enterprise-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractorOnboardingRoute = ContractorOnboardingRouteImport.update({
  id: '/contractor-onboarding',
  path: '/contractor-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorAdminRoute = ContractorAdminRouteImport.update({
  id: '/contractor-admin',
  path: '/contractor-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTransformationRoute = CareerTransformationRouteImport.update({
  id: '/career-transformation',
  path: '/career-transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const AygulQuizRoute = AygulQuizRouteImport.update({
  id: '/aygul-quiz',
  path: '/aygul-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aygul-quiz': typeof AygulQuizRoute
  '/career-transformation': typeof CareerTransformationRoute
  '/careers': typeof CareersRoute
  '/contractor-admin': typeof ContractorAdminRoute
  '/contractor-onboarding': typeof ContractorOnboardingRoute
  '/enterprise-transformation': typeof EnterpriseTransformationRoute
  '/learning-transformation': typeof LearningTransformationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/people_test': typeof People_testRoute
  '/people_test_review': typeof People_test_reviewRoute
  '/pmp-practice': typeof PmpPracticeRoute
  '/pmp24q40m': typeof Pmp24q40mRoute
  '/vizhun': typeof VizhunRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aygul-quiz': typeof AygulQuizRoute
  '/career-transformation': typeof CareerTransformationRoute
  '/careers': typeof CareersRoute
  '/contractor-admin': typeof ContractorAdminRoute
  '/contractor-onboarding': typeof ContractorOnboardingRoute
  '/enterprise-transformation': typeof EnterpriseTransformationRoute
  '/learning-transformation': typeof LearningTransformationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/people_test': typeof People_testRoute
  '/people_test_review': typeof People_test_reviewRoute
  '/pmp-practice': typeof PmpPracticeRoute
  '/pmp24q40m': typeof Pmp24q40mRoute
  '/vizhun': typeof VizhunRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aygul-quiz': typeof AygulQuizRoute
  '/career-transformation': typeof CareerTransformationRoute
  '/careers': typeof CareersRoute
  '/contractor-admin': typeof ContractorAdminRoute
  '/contractor-onboarding': typeof ContractorOnboardingRoute
  '/enterprise-transformation': typeof EnterpriseTransformationRoute
  '/learning-transformation': typeof LearningTransformationRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/people_test': typeof People_testRoute
  '/people_test_review': typeof People_test_reviewRoute
  '/pmp-practice': typeof PmpPracticeRoute
  '/pmp24q40m': typeof Pmp24q40mRoute
  '/vizhun': typeof VizhunRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aygul-quiz'
    | '/career-transformation'
    | '/careers'
    | '/contractor-admin'
    | '/contractor-onboarding'
    | '/enterprise-transformation'
    | '/learning-transformation'
    | '/payment-success'
    | '/people_test'
    | '/people_test_review'
    | '/pmp-practice'
    | '/pmp24q40m'
    | '/vizhun'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aygul-quiz'
    | '/career-transformation'
    | '/careers'
    | '/contractor-admin'
    | '/contractor-onboarding'
    | '/enterprise-transformation'
    | '/learning-transformation'
    | '/payment-success'
    | '/people_test'
    | '/people_test_review'
    | '/pmp-practice'
    | '/pmp24q40m'
    | '/vizhun'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aygul-quiz'
    | '/career-transformation'
    | '/careers'
    | '/contractor-admin'
    | '/contractor-onboarding'
    | '/enterprise-transformation'
    | '/learning-transformation'
    | '/payment-success'
    | '/people_test'
    | '/people_test_review'
    | '/pmp-practice'
    | '/pmp24q40m'
    | '/vizhun'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AygulQuizRoute: typeof AygulQuizRoute
  CareerTransformationRoute: typeof CareerTransformationRoute
  CareersRoute: typeof CareersRoute
  ContractorAdminRoute: typeof ContractorAdminRoute
  ContractorOnboardingRoute: typeof ContractorOnboardingRoute
  EnterpriseTransformationRoute: typeof EnterpriseTransformationRoute
  LearningTransformationRoute: typeof LearningTransformationRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  People_testRoute: typeof People_testRoute
  People_test_reviewRoute: typeof People_test_reviewRoute
  PmpPracticeRoute: typeof PmpPracticeRoute
  Pmp24q40mRoute: typeof Pmp24q40mRoute
  VizhunRoute: typeof VizhunRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vizhun': {
      id: '/vizhun'
      path: '/vizhun'
      fullPath: '/vizhun'
      preLoaderRoute: typeof VizhunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmp24q40m': {
      id: '/pmp24q40m'
      path: '/pmp24q40m'
      fullPath: '/pmp24q40m'
      preLoaderRoute: typeof Pmp24q40mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmp-practice': {
      id: '/pmp-practice'
      path: '/pmp-practice'
      fullPath: '/pmp-practice'
      preLoaderRoute: typeof PmpPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people_test_review': {
      id: '/people_test_review'
      path: '/people_test_review'
      fullPath: '/people_test_review'
      preLoaderRoute: typeof People_test_reviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people_test': {
      id: '/people_test'
      path: '/people_test'
      fullPath: '/people_test'
      preLoaderRoute: typeof People_testRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-transformation': {
      id: '/learning-transformation'
      path: '/learning-transformation'
      fullPath: '/learning-transformation'
      preLoaderRoute: typeof LearningTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-transformation': {
      id: '/enterprise-transformation'
      path: '/enterprise-transformation'
      fullPath: '/enterprise-transformation'
      preLoaderRoute: typeof EnterpriseTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-onboarding': {
      id: '/contractor-onboarding'
      path: '/contractor-onboarding'
      fullPath: '/contractor-onboarding'
      preLoaderRoute: typeof ContractorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-admin': {
      id: '/contractor-admin'
      path: '/contractor-admin'
      fullPath: '/contractor-admin'
      preLoaderRoute: typeof ContractorAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-transformation': {
      id: '/career-transformation'
      path: '/career-transformation'
      fullPath: '/career-transformation'
      preLoaderRoute: typeof CareerTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aygul-quiz': {
      id: '/aygul-quiz'
      path: '/aygul-quiz'
      fullPath: '/aygul-quiz'
      preLoaderRoute: typeof AygulQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AygulQuizRoute: AygulQuizRoute,
  CareerTransformationRoute: CareerTransformationRoute,
  CareersRoute: CareersRoute,
  ContractorAdminRoute: ContractorAdminRoute,
  ContractorOnboardingRoute: ContractorOnboardingRoute,
  EnterpriseTransformationRoute: EnterpriseTransformationRoute,
  LearningTransformationRoute: LearningTransformationRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  People_testRoute: People_testRoute,
  People_test_reviewRoute: People_test_reviewRoute,
  PmpPracticeRoute: PmpPracticeRoute,
  Pmp24q40mRoute: Pmp24q40mRoute,
  VizhunRoute: VizhunRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
